alias g='git'
alias gst='git status'
alias gsw='git switch'
alias gl='git pull'
alias gp='git push'
alias gco='git checkout'
alias gb='git branch'
alias glg='git log --stat --max-count=5'
alias glgg='git log --graph --max-count=5'
alias gss='git status -s'
alias ga='git add'
